name = "juno"
version = "1.4.0"

description = "Flexible JSON decoding for Gleam"
licences = ["Apache-2.0"]
links = [{ title = "Gleam", href = "https://gleam.run" }]
repository = { type = "github", user = "massivefermion", repo = "juno" }

[dependencies]
gleam_json = "~> 2.0"
gleam_stdlib = ">= 0.49.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.2"
